### ISSUE TITLE
mbit == 1 000 000 bits

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beradrian/jsbandwidth#1]
```

http://en.wikipedia.org/wiki/Megabit

To get Mbit, one should divide /(1000*1000) instead of /(1024*1024).

Please fix it in default.htm


```

Original issue reported on code.google.com by `s.ivlen...@gmail.com` on 9 Jul 2010 at 7:01

**Comment by beradrian** [comment]
The speed is returned now in bps, not Mbps. If you want to convert it you should use https://github.com/gentooboontoo/js-quantities.
