### ISSUE TITLE
Create working demo in nodejs and Spring

### ISSUE THREAD

**Issue by unseen1980** [beradrian/jsbandwidth#10]
Hi,

Do I have to create a new route '/test' in server? I created a simple webserver with express which serves static files.

```
var express = require('express');
var app = express();
app.use(express.static('client'));
app.listen(2222);
console.log('Server running at http://localhost:2222/');
```

But I am getting a 404. It makes a request in this http://localhost:2222/test?id=1448291994940

A working demo would be appreciated.

**Comment by uniquegodwin** [comment]
yes, I would appreciate the same, a working demo.

Also, why do we need other programming platforms such as php / JAVA /asp.net for post? Can't we just send a post request to node.js express?

**Comment by carloscarcamo** [comment]
+1

**Comment by beinto** [comment]
does this module just runs with node.js? can we use it inside a html page?

**Comment by beradrian** [comment]
Yes, it can be used in a html page. And it can be used with any web server.

**Comment by beinto** [comment]
sorry, but I still cannot generate a .js that can be used. it gives me an error that exports is not defined
