### ISSUE TITLE
r.then is not a function

### ISSUE THREAD

**Issue by TiagoGouvea** [beradrian/jsbandwidth#7]
I've got a Uncaught TypeError: `r.then is not a function`, after the warning `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. `.

And then, the script stop running.

Testing on chrome with local javascript file.

**Comment by beradrian** [comment]
Are you running this from a server? This is not designed to work locally (with file://).

**Comment by TiagoGouvea** [comment]
I'm runnig in http://localhost/myproject/, the downloadUrl are remote.

**Comment by beradrian** [comment]
I released a new version. Do you still have the issue?

**Comment by beradrian** [comment]
I moved XhrPromise to an external package https://github.com/beradrian/xhrpromise. Now you shouldn't have this issue anymore. I will close it, but please feel free to comment to reopen it.
